### ISSUE TITLE
Allow ZapPlanner to prefill data

### ISSUE THREAD

**Issue by rolznz** [getAlby/ZapPlanner#11]
Something like this, where user just needs to authorize the NWC connection to setup the new subscription:
```
[zapplanner.com?recipient=foobar&payerdata={](http://zapplanner.com/?recipient=foobar&payerdata={)"foo"="bar"}&comment=baz&timeframe=30d
```

**Comment by bumi** [comment]
With that I think it should not be a prefilling of the form but it should just be the confirmation screen.

a website then could have a button "setup recurring payment with zapplanner" which links to zapplanner. 
zapplanner then asks the user for confirmation by requesting the NWC connection 
done

**Comment by rolznz** [comment]
(Lower priority)

We can add an optional `returnUrl` that will be shown as a link on the subscription page:

"Return to [example.com](http://example.com/)"

**Comment by rolznz** [comment]
Currently all the fields get validated in the previous screen. These validations wouldn't happen currently since the link would be directly to the confirmation page. The validation should happen there too.

**Comment by bumi** [comment]
In Rails we would have a model which takes care of the data and is the point where data is validated. 
don't we also have some "model" "class" here?

**Comment by rolznz** [comment]
> In Rails we would have a model which takes care of the data and is the point where data is validated. don't we also have some "model" "class" here?
> 
> and isn't is saved in the second step? so the validation on the first step is only for the user? I could still post invalid data which then gets saved?

 There is only form validation right now. There's no validation on the model before it is saved. I will look into it.

**Comment by bumi** [comment]
ah, I see. I guess it's also not very important. we mainly need to make sure that our code does not break because of invalid data.

**Comment by rolznz** [comment]
I addressed this and added validation in the create subscription endpoint in https://github.com/getAlby/ZapPlanner/pull/14
