### ISSUE TITLE
disable submit buttons or add spinner on loading

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#18]
Currently the user does not get feedback when the page is loaded. 
I click on the submit button and it takes a bit until I get feedback. 
maybe we can disable the submit button or add a loading spinner to indicate to the user that something is loading

**Comment by rolznz** [comment]
fixed by https://github.com/getAlby/ZapPlanner/commit/d2eaf5cc5e7b817d33ddecc3b272ee5b0c8b8e54
