### ISSUE TITLE
change "link wallet" to some Alby branded button

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#26]
The link wallet uses the Alby NWC app, so we should indicate this here.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/318/235978412-a7f7ad1d-8c69-4020-bba3-d8b87db8b57e.png">

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/ZapPlanner/pull/27
