### ISSUE TITLE
Some react issue when lnurl fields are not shown

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#34]
<img width="411" alt="image" src="https://github.com/getAlby/ZapPlanner/assets/318/bc788d02-3c20-451c-a8eb-175d0ef89da6">

this is likely because that ln address does not have support for name/comment

**Comment by rolznz** [comment]
fixed in https://github.com/getAlby/ZapPlanner/commit/b69987e5d176ba6099b404ed563f61cd5b191e6c
