### ISSUE TITLE
Remove seconds as option

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#36]
I don't think it makes sense to send payments every second (payments can even take longer than that). We should event prevent that and only allow something reasonable. 

A week would be a better additional option than seconds or minutes, imo.

**Comment by rolznz** [comment]
fixed in https://github.com/getAlby/ZapPlanner/commit/1942841e7fba86a057d6f4034cf7729f55e811df and https://github.com/getAlby/ZapPlanner/commit/2360cef8f6e45071fd474e9c1dd4ca15b28f6ffb
