### ISSUE TITLE
Pay multiple recipients in one go

### ISSUE THREAD

**Issue by rolznz** [getAlby/ZapPlanner#47]
How should this work? multiple subscriptions that live in a group? or one subscription with multiple recipients and splits?

**Comment by bumi** [comment]
I don't think this is something that should go in here. It just makes the product more complicated.

**Comment by rolznz** [comment]
Closing this, I agree another service dedicated to splitting zaps would be cool. It's a general problem which other people have asked for a solution for in different situations.
