### ISSUE TITLE
Improve emails for failure & recovery

### ISSUE THREAD

**Issue by rolznz** [getAlby/ZapPlanner#51]
-[ ] Add the number of failure attempts to the fail email (Attempt 1/3)
-[ ] Consider updating success template to show recovered status (after one or more failures)
-[ ] Add email template for on re-activating subscription

**Comment by bumi** [comment]
got an email without retry count: 
<img width="591" alt="image" src="https://github.com/getAlby/ZapPlanner/assets/318/7ebea46c-878c-4729-987f-005496b07e4a">

**Comment by bumi** [comment]
would be nice to tell users the error message

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/ZapPlanner/commit/7cfe66a7af04d72c65adc01a520c7a9108c835bf
