### ISSUE TITLE
PayerName must be name in LUD18 params

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#53]
Somehow I think zapplanner is currently saving the payer's name in `payerName` by the LNURL spec this must be sent as  `name`.

https://github.com/getAlby/ZapPlanner/blob/72aa24af282ce2d30afe03e3cf3501edb33fc34a/app/create/components/CreateSubscriptionForm.tsx#L49-L53

spec: https://github.com/lnurl/luds/blob/luds/18.md
alby-tools type: https://github.com/getAlby/alby-tools/blob/master/src/types.ts#L36

**Comment by rolznz** [comment]
@bumi thanks for catching that. Fixed here: https://github.com/getAlby/ZapPlanner/commit/6288d6f29c19293d51832244d2e04c03b32339b4

**Comment by rolznz** [comment]
I also updated the existing rows (30 rows) in the database with this issue.
