### ISSUE TITLE
Allow message and name only if the lightning address supports it

### ISSUE THREAD

**Issue by bumi** [getAlby/ZapPlanner#9]
when we validate the ln address (#8) we load the lnurlp data.
With that we can also check if the lightning address supports a comment and only if it is supported we allow the user to add a message. 
Same can be added for a name

**Comment by rolznz** [comment]
@bumi for the name, is that payerData.name from LUD-18? great!

I added a PR here which would be good to more easily check these things: https://github.com/getAlby/alby-tools/pull/25

**Comment by rolznz** [comment]
This has been completed in https://github.com/getAlby/ZapPlanner/pull/14
